# Generated by Django 4.0.6 on 2022-07-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_alter_product_bolt_circle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='AA00001', max_length=8)),
                ('date', models.DateField()),
                ('invoice_paid', models.BooleanField()),
                ('invoice_paid_confirmed', models.BooleanField()),
                ('amount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('btw_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount_total_with_btw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=254)),
                ('registration_number_or_btw_number', models.PositiveIntegerField(blank=True, default=1, primary_key=True, serialize=False)),
                ('street_adress_1', models.IntegerField(blank=True, default=0)),
                ('street_adress_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('default_opgeld', models.IntegerField(default=17)),
            ],
            options={
                'verbose_name_plural': 'Suplier',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('opgeld_on_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('lineitem_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('btw', models.BooleanField(default=True)),
                ('btw_on_item', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('lineitem_total_with_btw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='invoices.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='suplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplier', to='invoices.suplier'),
        ),
    ]
