# Generated by Django 4.0.6 on 2022-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='btw_on_opgeld',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='default_opgeld',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
