# Generated by Django 4.0.6 on 2022-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoiceitem_btw_on_opgeld_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='opgeld_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
