# Generated by Django 4.0.6 on 2022-07-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_opgeld_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount_total',
            new_name='invoice_total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
