# Generated by Django 4.0.6 on 2022-07-09 18:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='AA001', max_length=6, unique=True)),
                ('name', models.CharField(default='name', max_length=100)),
                ('description', models.CharField(default='description', max_length=256)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tires', models.BooleanField(default=True)),
                ('season', models.CharField(choices=[('1', 'Summer'), ('2', 'Winter'), ('3', 'All Season')], default='Summer', max_length=11)),
                ('width', models.IntegerField(default='000', validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
                ('height', models.IntegerField(default='00', validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinLengthValidator(2)])),
                ('diameter', models.IntegerField(default='00', validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinLengthValidator(2)])),
                ('full_size', models.CharField(default='000/00R00', max_length=10)),
                ('full_size_display', models.CharField(default='000/00 R00', max_length=10)),
                ('dot', models.IntegerField(default='000', validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)])),
                ('profiel_1', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('profiel_2', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('profiel_3', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('profiel_4', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('rims', models.BooleanField(default=True)),
                ('rim_diameter', models.IntegerField(default='00', validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinLengthValidator(2)])),
                ('rim_width', models.CharField(default='0.0J', max_length=4)),
                ('oe_rims', models.BooleanField(default=False)),
                ('oe_number', models.CharField(max_length=50)),
                ('stud_count', models.IntegerField(default='0', validators=[django.core.validators.MaxLengthValidator(1), django.core.validators.MinLengthValidator(1)])),
                ('bolt_circle', models.IntegerField(default='000', validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(2)])),
                ('bolt_pattern', models.CharField(max_length=5)),
                ('offset', models.IntegerField(default='00', validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(2)])),
                ('centre_bore', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('purchase_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=4)),
                ('extra_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('full_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('archived', models.BooleanField(default=False)),
                ('sold_date', models.DateField()),
                ('sold_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('purchase_document', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.manufacturer')),
                ('rim_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.cars')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
