# Generated by Django 4.0.6 on 2022-07-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cars_manufacturer_category_category_code_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='AA0001', max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='ExtraCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='extra_costs_product', to='products.product')),
            ],
        ),
    ]
