# Generated by Django 4.0.6 on 2022-07-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_bolt_circle_alter_product_centre_bore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mp',
            field=models.BooleanField(default=False),
        ),
    ]
