# Generated by Django 4.0.6 on 2022-07-10 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_diameter_alter_product_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bolt_circle',
            field=models.IntegerField(blank=True, default='000', null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(98)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='AA0001', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='oe_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offset',
            field=models.IntegerField(blank=True, default='00', null=True, validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(-15)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rim_diameter',
            field=models.IntegerField(blank=True, default='00', null=True, validators=[django.core.validators.MaxValueValidator(26), django.core.validators.MinValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rim_width',
            field=models.CharField(blank=True, default='0.0J', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stud_count',
            field=models.IntegerField(blank=True, default='0', null=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(3)]),
        ),
    ]
