# Generated by Django 4.0.6 on 2022-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_bolt_circle_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bolt_circle',
            field=models.CharField(blank=True, default='0', max_length=4, null=True),
        ),
    ]
