# Generated by Django 4.0.6 on 2022-07-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_bolt_circle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bolt_circle',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
